### ISSUE TITLE
Add `setup-java` steps to example workflows

### ISSUE THREAD

**Issue by bigdaz** [gradle/actions#115]
Users should be explicit about the version of Java they use to build their projects, and our samples should encourage this best practise.

**Comment by danielr1996** [comment]
stumbled across this issue while researching the error "the consumer was configured to find a library for use during runtime, compatible with Java 11", as it turns out the gradle ships with its own jvm (11) that will be used if no other distribution is supplied.
Adding ```
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
```
solved the issue for me.
