### ISSUE TITLE
Automatically perform wrapper validation check in `setup-gradle`

### ISSUE THREAD

**Issue by bigdaz** [gradle/actions#12]
Currently, we recommend that users configure a separate workflow running the [wrapper-validation-action](https://github.com/marketplace/actions/gradle-wrapper-validation) to verify that the Gradle wrapper jar is not corrupted.

Doing this automatically for any workflow using `setup-gradle` and `dependency-submission` would increase coverage of wrapper validation and reduce the complexity for users adopting Gradle with GitHub actions. The functionality already exists with the `validate-wrappers` parameter: this issue is about enabling this by default.

Issues outstanding to allow this:
- #281 
- #172

**Comment by JLLeitschuh** [comment]
@bigdaz this looks like it may be possible now that Gradle publishes snapshot checksums, right?

**Comment by leonard84** [comment]
> I think the biggest thing blocking this from happening is that currently Gradle doesn't publish wrapper SHAs for SNAPSHOT releases. As such, projects like gradle/gradle can't use the verification action because it is regularly using pre-release builds to build Gradle.

If they are still not published, this could easily be mitigated by introducing a switch to disable wrapper validation for SNAPSHOT versions or completely. However, having validation enabled by default would make everyone safer.
