### ISSUE TITLE
Job Summary shows many unrelated projects on self-hosted runner

### ISSUE THREAD

**Issue by nnellanspdl** [gradle/actions#127]
Please see example screenshot below.  This is just a small snippet, there are hundreds of projects listed here.  This happens for each of our builds.

We use self-hosted runners that are long-lived / not ephemeral.

Two of my initial thoughts are a cluttered cache, or a cluttered gradle home.

I've tried to resolve the gradle home issue by running the following first in my workflow:
`rm -rf ~/.gradle`
However, this doesn't change anything for me.

![image](https://github.com/gradle/actions/assets/88901593/de5d323f-0017-4886-b691-65726dba10d3)

**Comment by bigdaz** [comment]
@nnellanspdl Each Gradle build writes a results JSON file to `$RUNNER_TEMP/.build-results`. 
The action then iterates over these to generate the job summary.

I guess we should either clean these up after the job completes, or make the directory unique for a Job invocation.

Pending a fix in the action, you can ensure that `$RUNNER_TEMP/.build-results` is cleared after each job. You shouldn't need to remove the `~/.gradle` directory.

**Comment by nnellanspdl** [comment]
Clearing that worked, thanks!

**Comment by bigdaz** [comment]
This is still something we should address in the action implementation.

**Comment by bigdaz** [comment]
Fixed in #133
