### ISSUE TITLE
Java toolchain cache entries are not differentiated by architecture

### ISSUE THREAD

**Issue by hfhbd** [gradle/actions#138]
If you use a matrix with different RUNNER_ARCHs, like `macos-latest` (x64) and `macos-14` (M1), the jdk cache is restored but it is specific to the arch causing a cache miss.

**Comment by hfhbd** [comment]
> I think you're saying that the same 'java-toolchains' cache entry published from macos-latest will be restored on a later job running on macos-14. But this restored toolchain is specific to the x64 architecture and thus cannot be used on macos-14.

Yes, exactly.

I will test it, but according to the docs, `enableCrossOsArchive` is only about Windows:
```
enableCrossOsArchive - An optional boolean when enabled, allows Windows runners to save or restore caches that can be restored or saved respectively on other platforms.
```
I also don't know, if GitHub uses RUNNER_ARCH at all, because `macos-14` is the first public runner using arm, beside the private Linux/Windows beta.

**Comment by bigdaz** [comment]
OK thanks for clarifying. 
If you're interested in submitting a PR, then I in the end we'll need to have this context when generating the cache key here: https://github.com/gradle/actions/blob/main/sources/src/caching/gradle-home-extry-extractor.ts#L225-L227

A simple approach might be to simply append the `RUNNER_ARCH` value to the 'artifactType' for this entry: so you'd have `artifactType == 'java-toolchains-x86'`.
