### ISSUE TITLE
Cache checksums after they have been fetched

### ISSUE THREAD

**Issue by bigdaz** [gradle/actions#172]
Currently, if a checksum isn't in the "known" list, we fetch every time.
We could cache the results to avoid this unnecessary work.

**Comment by bgalek** [comment]
are you accepting contributions? :)

**Comment by bigdaz** [comment]
Yes PRs are always welcome!

**Comment by bigdaz** [comment]
@bgalek If you're diving into this area, it might be worth looking at #171 before this one.

**Comment by bgalek** [comment]
Perfect, I'll look into it!
