### ISSUE TITLE
Dependency-submission setup recursively.

### ISSUE THREAD

**Issue by ncolonm** [gradle/actions#208]
Hello, 

I need some help trying to setup the dependency-submission action in a manner that when it runs, it searches for every `build.gradle` file, creates a dependency graph and makes a review of them. I've been able to set it up when just 1 `build.gradle` is found in the root directory of the repo, but don't know how to make it work in this type of structure I described before.

**Comment by bigdaz** [comment]
I don't really understand what you mean. A Gradle project consists of a single `settings.gradle` file and multiple `build.gradle` files. All of the `build.gradle` files will contribute to the same dependency graph.
