### ISSUE TITLE
Does the build scan will reveal the secret key?

### ISSUE THREAD

**Issue by iseki0** [gradle/actions#237]
I found you store the `GRADLE_ENCRYPTION_KEY` into the environment variable.
![image](https://github.com/gradle/actions/assets/13687964/e0d2ad2d-fd46-4930-8a58-91ce2f4bbbed)
Is it a problem?

**Comment by bigdaz** [comment]
No, environment variables are not exposed in Build Scans. Your secrets will not be leaked unless you write them to the console.
