### ISSUE TITLE
Multiple GRADLE_USER_HOMEs

### ISSUE THREAD

**Issue by KlemenDEV** [gradle/actions#264]
We have a special project where we use multiple GRADLE_USER_HOMEs.

Is there a way to configure the gradle-setup action to cache multiple GRADLE_USER_HOME folders?

**Comment by bigdaz** [comment]
This action will honor the `GRADLE_USER_HOME` env var if it is set prior to the `setup-gradle` step. But there's no way to have a single `setup-gradle` step that handles multiple Gradle User Home directories, and it's not supported to have multiple `setup-gradle` steps in the same workflow Job.

So your best option is to have multiple jobs, each one with a different `GRADLE_USER_HOME` directory specified. This could be done via a matrix.
