### ISSUE TITLE
Link to build scans are not reported in Job Summary

### ISSUE THREAD

**Issue by warting** [gradle/actions#275]
Build scans is published but setup gradle does not retreive the url.

Versions used:
- Gradle 8.8
- gradle/actions/setup-gradle@v3
- com.gradle:develocity-gradle-plugin:3.17.5
- Develocity 2024.1.5

![image](https://github.com/gradle/actions/assets/657973/246a3f1e-46b4-41f9-b9e1-43c26d6bd3d5)
![image](https://github.com/gradle/actions/assets/657973/89791892-65ce-4db1-9a78-1f2e5a76a7ae)

**Comment by bigdaz** [comment]
Thanks for the report.
We have test coverage for this combination of versions, so there must be something about your project that is causing this to fail.

The Job Summary functionality works via Gradle init scripts, which are automatically injected into Gradle User Home. These init-scripts write a results file to `$RUNNER_TEMP/.build-results`.

Can you please check the following:
1. Do you see "[gradle action failed to write build-results file](https://github.com/gradle/actions/blob/main/sources/src/resources/init-scripts/gradle-actions.build-result-capture.init.gradle#L166)" in your Gradle output?
2. Add a step following the Gradle invocation to list the results of the `$RUNNER_TEMP/.build-results` directory? 
3. In the same step, `cat` all of the `.json` files in `.build-results` to check contents. These JSON files should contain the Build Scan link but I assume in your case they do not.

The added step would look something like this (untested):
```
    - name: Print build results
      working-directory: ${{ env.RUNNER_TEMP }}
      shell: bash
      run: |
        echo "RUNNER_TEMP = $RUNNER_TEMP"
        ls -la $RUNNER_TEMP
        ls -la $RUNNER_TEMP/.build-results
        find $RUNNER_TEMP/.build-results -name *.json -type f -exec cat {} \;
        echo ""

Once I have a better feel for where this might be failing, I can publish a release with some additional logging to help dig deeper.

**Comment by bigdaz** [comment]
@warting Have you been able to work out what might be causing this? Do you have any custom init-scripts written to `~/.gradle/init.d`?

Without further details of your issue it's difficult to see how it can be fixed.

**Comment by bigdaz** [comment]
@warting I'm going to close this issue as non-reproducible. If you have more details that might help us track down the underlying problem, please comment here and I'll be happy to reopen.
