### ISSUE TITLE
The `setup-gradle` action should make it easy to run with wrapper in an OS-agnostic way

### ISSUE THREAD

**Issue by bigdaz** [gradle/actions#308]
Now that the `arguments` parameter has been removed, it's inconvenient to write a matrix Job that tests against Windows and Ubuntu. This is because the execution step needs to differentiate between `./gradlew` on Ubuntu and `gradlew.bat` on Windows.

To fix this, we should:
- Fix #273 so that setting the version to `wrapper` allows the `gradle` command to execute a local wrapper if available.
- Make `gradle-version: wrapper` the default.

We could also make `gradle-version: wrapper` to fail if no wrapper is present, and have `gradle-version: wrapper-or-path` as the default.

**Comment by cloudshiftchris** [comment]
Is there a need to even consider `gradlew.bat`?

This works fine on Windows runners to execute the wrapper:

```
      - name: Execute Gradle
        shell: bash
        run: |
          ./gradlew build
```

**Comment by bigdaz** [comment]
@cloudshiftchris You're absolutely correct. Even without the explicit `shell` configuration, the default shell on Windows (`pwsh`) runs `./gradlew` just fine.

This issue was reported to me and I didn't test it until now :).
