### ISSUE TITLE
Wrapper validation fails for repos with unmappable characters in file names

### ISSUE THREAD

**Issue by sschuberth** [gradle/actions#366]
As part of our project we have committed test assets that deliberately contain unmappable characters as part of their file name, see [this](https://github.com/oss-review-toolkit/ort/pull/9067/commits/a04cef35c8dd17f396f881e202f5e1dea188c1c9). When running the wrapper validation (or in fact also the Gradle setup), CI fails with [this](https://github.com/oss-review-toolkit/ort/actions/runs/10678708849/job/29596323721?pr=9067#step:3:77):

```
Run gradle/actions/wrapper-validation@16bf8bc8fe830fa669c3c9f914d3eb147c629707
Error: Error: ENOENT: no such file or directory, lstat '/home/runner/work/ort/ort/utils/common/src/test/assets/unmappable-characters/testu��es.txt'
Error: ENOENT: no such file or directory, lstat '/home/runner/work/ort/ort/utils/common/src/test/assets/unmappable-characters/testu��es.txt'
    at Object.lstatSync (node:fs:1633:25)
    at /home/runner/work/_actions/gradle/actions/16bf8bc8fe830fa669c3c9f914d3eb147c629707/dist/wrapper-validation/main/index.js:127651:19
    at Array.map (<anonymous>)
    at recursivelyListFiles (/home/runner/work/_actions/gradle/actions/16bf8bc8fe830fa669c3c9f914d3eb147c629707/dist/wrapper-validation/main/index.js:127649:59)
    at async Promise.all (index 9)
    at async recursivelyListFiles (/home/runner/work/_actions/gradle/actions/16bf8bc8fe830fa669c3c9f914d3eb147c629707/dist/wrapper-validation/main/index.js:127649:27)
    at async Promise.all (index 0)
    at async recursivelyListFiles (/home/runner/work/_actions/gradle/actions/16bf8bc8fe830fa669c3c9f914d3eb147c629707/dist/wrapper-validation/main/index.js:127649:27)
    at async Promise.all (index 1)
    at async recursivelyListFiles (/home/runner/work/_actions/gradle/actions/16bf8bc8fe830fa669c3c9f914d3eb147c629707/dist/wrapper-validation/main/index.js:127649:27)
```

Could such error be ignored / turned into a warning instead of making the action fail?

**Comment by bigdaz** [comment]
Does this still fail if you disable wrapper validation?

```
      with:
        validate-wrappers: false
```

**Comment by sschuberth** [comment]
Apparently that works.

I should also not that I'm not using `validate-wrappers: true` on `gradle/actions/setup-gradle`, but `gradle/actions/wrapper-validation` directly, if that makes a difference.

**Comment by sschuberth** [comment]
BTW, the file I'm using for testing can be cloned from https://github.com/fshost/node-dir/tree/a57c3b1b571dd91f464ae398090ba40f64ba38a2/test/fixtures/testdir5.

**Comment by bigdaz** [comment]
@sschuberth I tried to clone the repo in order to reproduce this, and that wasn't even possible

```
~/dev/playground ❯ git clone git@github.com:fshost/node-dir.git
Cloning into 'node-dir'...
remote: Enumerating objects: 368, done.
remote: Total 368 (delta 0), reused 0 (delta 0), pack-reused 368 (from 1)
Receiving objects: 100% (368/368), 67.10 KiB | 369.00 KiB/s, done.
Resolving deltas: 100% (167/167), done.
error: unable to create file test/fixtures/testdir5/testu��es.txt: Illegal byte sequence
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

How did you manage to get those files committed?
Can you provide a PR that will add the files to this repo? Just the presence of the file somewhere like `sources/test/data` should be enough to trigger this failure when wrapper-validation is carried out on the repo itself.

**Comment by bigdaz** [comment]
I suspect that something like this might resolve the issue: https://github.com/gradle/actions/pull/388

Are you able to test it locally?

**Comment by sschuberth** [comment]
> I tried to clone the repo in order to reproduce this, and that wasn't even possible

Are you on macOS maybe?

> How did you manage to get those files committed?

I did nothing special, just cloning https://github.com/fshost/node-dir.git worked for me on Fedora Linux 40 with Git 2.46.0, and I was able to copy over that file to my own repo, and commit it.

> Can you provide a PR that will add the files to this repo?

Here you go: https://github.com/gradle/actions/pull/391.

> Are you able to test it locally?

Not sure how. You mean with https://github.com/nektos/act?

**Comment by sschuberth** [comment]
> > Can you provide a PR that will add the files to this repo?
> 
> Here you go: [#391](https://github.com/gradle/actions/pull/391).

Any update @bigdaz? Does that PR help you to move forward?

**Comment by bigdaz** [comment]
@sschuberth I believe this issue should be fixed by #438. 
It appears that my use of MacOS prevents me from testing this, and I cannot open/clone any Git branch containing the illegal file.

Can you please try running with `gradle/actions/wrapper-validation@main` and see if the issue is resolved for you?

**Comment by sschuberth** [comment]
> Can you please try running with `gradle/actions/wrapper-validation@main` and see if the issue is resolved for you?

Still [seems to fail](https://github.com/oss-review-toolkit/ort-test-fork-node-dir/actions/runs/11817102968/job/32921816772#step:3:13).

**Comment by sschuberth** [comment]
> Will try with `gradle/actions/wrapper-validation@main` again.

That [works](https://github.com/oss-review-toolkit/ort-test-fork-node-dir/actions/runs/11817187578/job/32922069898#step:3:6)! And it even recognizes the wrapper that's committed to the same directory as the file with unmappable characters 👍🏻
