### ISSUE TITLE
Exclude detached configurations from dependency graph

### ISSUE THREAD

**Issue by JordanLongstaff** [gradle/actions#390]
Ever since I added [dependency graph submission from Gradle](https://github.com/JordanLongstaff/ArtemisAgent/commit/a8bbea584f410dcf1e10ca61c50b89961b640003) into my GitHub workflow, security vulnerabilities have been reported that are making dependency review fail in my repo. Worse, most of these vulnerabilities were supposedly fixed previously by [adding dependency constraints](https://github.com/JordanLongstaff/ArtemisAgent/commit/bb18aa892efe272530ddb08ad4850e4882ea2595) into my build scripts.

I looked into the packages that were causing the vulnerabilities and I found that they are used in a detached configuration. It seems they are used in the Android Gradle `lint` tasks, because they are dependencies of `com.android.tools.lint:lint-gradle`. For reference, [here is the build scan](https://scans.gradle.com/s/ox2auwckwyely/dependencies?dependencies=commons-compress&expandAll&focusedDependency=WzE3LDE3LDIyNTQsWzAsMCxbMF1dXQ&focusedDependencyView=versions) that I used to trace the vulnerable packages. It is focused on the package of highest severity, as [reported here](https://github.com/JordanLongstaff/ArtemisAgent/security/dependabot/8).

Google seems to either be unaware of these vulnerabilities or have no interest in fixing them (I checked the latest stable and pre-release versions of their packages, and none of them address the issues) and my Internet searching has failed to turn up any way to constrain the dependencies to versions that patch the vulnerabilities, probably because they are in a detached configuration. My impression is that excluding detached configurations from the dependency graph is the only solution.

If this does not seem like a reasonable solution, I'm all ears for an alternative.

No, I am not using the Spring dependency management plugin, as mentioned [here](https://discuss.gradle.org/t/what-is-detachedconfiguration-i-have-a-lots-of-them-for-each-subproject-and-resolving-them-takes-95-of-build-time/31595/4).

**Comment by bigdaz** [comment]
Thanks for your report.
Can you please try excluding these dependencies programmatically and see if it resolves your issue?

```
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
      with:
        dependency-graph-exclude-configurations: 'detachedConfiguration.*'
```

**Comment by JordanLongstaff** [comment]
Wow. That did the trick. Thanks so much!

But seriously, Google, get with the program. 😑

**Comment by ncolonm** [comment]
Hey @bigdaz , this is a very interesting issue that it's happening with our organization. 

Question is, does it pose any risk to ignore the `detachedConfigurations` alerts? Or do you suggest us to go ahead and try to fix them other way?

**Comment by bigdaz** [comment]
@ncolonm There's no single answer. In some cases, a `detachedConfiguration` can be used simply to check which versions of a dependency are available, or to download a file, or some other operation that will not have any impact on your build.

In other cases, the `detachedConfiguration` could be resolving a jar that is directly used in your build logic or is included in your release.

I would always first try to resolve the issue by updating dependencies. If that's not possible, you could selectively ignore certain detached configurations (assuming you can differentiate between them).
