### ISSUE TITLE
Gradle 8.12-rc-1 deprecation in dependency graph

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/actions#487]
> Script '/home/runner/.gradle/init.d/gradle-actions.github-dependency-graph-gradle-plugin-apply.groovy': line 14
Space-assignment syntax in Groovy DSL has been deprecated. This is scheduled to be removed in Gradle 10.0. Use assignment ('url = <value>') instead. Consult the upgrading guide for further information: https://docs.gradle.org/8.12-rc-1/userguide/upgrading_version_8.html#groovy_space_assignment_syntax

https://github.com/TWiStErRob/net.twisterrob.ghlint/actions/runs/12371034803/job/34526318117#step:5:28

**Comment by bigdaz** [comment]
Thanks for the report. Looks like a simple tweak to the init-script is required [here](https://github.com/gradle/actions/blob/main/sources/src/resources/init-scripts/gradle-actions.github-dependency-graph-gradle-plugin-apply.groovy#L14).
