### ISSUE TITLE
Upgrade `undici` 

### ISSUE THREAD

**Issue by yogurtearl** [gradle/actions#54]
The current version of `undici` being used is being flagged for this vulnerability: 

see https://github.com/gradle/actions/blob/main/sources/package-lock.json#L8737

and https://github.com/nodejs/undici/security/advisories/GHSA-9f24-jqhm-jfcw

**Comment by erichaagdev** [comment]
Thank you for the report @yogurtearl. We'll look into addressing this.

**Comment by bigdaz** [comment]
It looks like our dependabot configuration is no longer correct, since we moved all npm config/sources into the 'sources' directory. This explains why we didn't get a Dependabot PR to upgrade.

**Comment by bigdaz** [comment]
Fixed in 9b415aef98da4037a37f1cfd34f7c50059ccdb3b
Note that this dependency update had no material impact on the generated action.
