### ISSUE TITLE
Build (windows-latest): `Failed to save: "C:\Program failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2`

### ISSUE THREAD

**Issue by tgrothe** [gradle/actions#59]
Hello,

we have the same problem in our matrix Windows gradle cache build. The warning appears with every run. As a workaround we have removed the option "cache: gradle".

Please see also:

https://github.com/Dungeon-CampusMinden/Dungeon/blob/4a13e21111e6c0a62d4bb0dfc65e257885ded40c/.github/workflows/github_ci.yml#L22
https://github.com/Dungeon-CampusMinden/Dungeon/issues/1354
https://github.com/Dungeon-CampusMinden/Dungeon/pull/1438

relates to https://github.com/gradle/gradle-build-action/issues/644

**Comment by erichaagdev** [comment]
Hi @tgrothe! The workflow you link to in your report is using the `actions/setup-java` action. You should report the issue there: https://github.com/actions/setup-java
