### ISSUE TITLE
Clearing Gradle caches on self-hosted runners

### ISSUE THREAD

**Issue by nnellanspdl** [gradle/actions#74]
This may not be the correct spot to request this, so please let me know if not.

I have a requirement to use private GitHub Runners, I can't use the github-hosted runners.  Also, my private runners are long-lived VMs that run many jobs over many weeks.

This results in a Gradle user home `~/.gradle` getting cluttered up over time.  Right now, I am manually cleaning this directory with a `run` step in my workflow.  I'm also curious what other directories Gradle uses to store historical data or caches, that I should also be cleaning?  Sorry, I'm fairly new to Gradle.

Has there been any thought to creating an action that could reset / clear all Gradle-related directories for a scenario such as mine?  GitHub-hosted Runners do not have this issue because they offer a clean VM for every job.

Thanks in advance.

**Comment by erichaagdev** [comment]
Hi @nnellanspdl. 👋 

Gradle itself will regularly cleanup unused files in its cache in persistent / non-ephemeral environments. You will find all of this described in the documentation: https://docs.gradle.org/current/userguide/directory_layout.html

If the caches are not being cleaned up frequently enough for your runners, you can reduce the retention period: https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home:configure_cache_cleanup

**Comment by nnellanspdl** [comment]
Thanks for the docs.  I think I will continue my method of using a `run` command to wipe out the directory each time.  My goal is to mimic the github-hosted runners in this aspect (a clean build every time).  Thanks again.
