### ISSUE TITLE
Create FAQ regarding `dependency-submission`

### ISSUE THREAD

**Issue by bigdaz** [gradle/actions#85]
When people use `gradle/actions/dependency-submission` for the first time, they have a lot of questions. We should attempt to provide answers in a FAQ.

Here's a start:

Q. **How can I tell if the `dependency-submission` action is working?**
A. Inspect the Dependency Graph for your project (Insights -> Dependency Graph). You should see some dependencies annotated with "Detected by GitHub Dependency Graph Gradle Plugin"

Q. **Why is "(Maven)" stated for all dependencies submitted by this action? I'm not using Maven.**
A. This simply indicates that the dependency was resolved from a standard Gradle/Maven artifact repository. It does not imply which build tool is used.

Q. **Why is every dependency attributed to `settings.gradle.kts`? All of my dependencies versions are declared in `build.gradle` / `libs.versions.toml` / `version.properties`.**
A. The attribution of all dependencies to the root settings file is due to a limitation in the GitHub Dependency Graph, which was modelled heavily on NPM and doesn't really map well to how Gradle projects declare and resolve dependencies. 
It is not possible for the dependency-submission action to accurately map each dependency version to a specific "manifest file" for 2 reasons:

- The Gradle events that are received when resolving dependencies don't contain this information. It may be possible (but difficult), to develop a plugin that extracts this information.
- The GitHub Dependency Submission API is not suitable for the Gradle model where: a) the same dependency can be declared and consumed in many build files and b) many files (including plugins) can contribute logic used to determine dependency versions.

We have long-term plans to improve the first point, and we are working with GitHub to resolve the second. However, at this stage the behaviour your are experiencing is what is expected.

Q. **The dependency graph contains a dependency that isn't anywhere in my build. Why is the action reporting dependencies I'm not using?**
A. If you see a particular dependency version in the dependency graph, this means your build is resolving that dependency at some point. You might be surprised what transitive dependencies are brought in by declared dependencies, including applied plugins.
[See here for a HOW-TO](https://github.com/gradle/actions/blob/main/dependency-submission/README.md#resolving-a-dependency-vulnerability) on getting the bottom of why the dependency is being resolved.

Q. **I see multiple versions of the same dependency in the dependency graph, but I'm only declaring a single version in my build. Why is the action reporting dependency versions I'm not using?**
A. This is almost certainly because the dependency in question **is actually being resolved with different versions** in different dependency configurations. For example, you may have one version brought in as a plugin dependency (resolved in the `classpath` configuration) and another used directly as a code dependency (resolved in the `compileClasspath` configuration).
[See here for a HOW-TO](https://github.com/gradle/actions/blob/main/dependency-submission/README.md#resolving-a-dependency-vulnerability) on getting the bottom of why the dependency is being resolved. By far the easiest way is to publish a Build Scan® for the workflow run: [this is easily achieved with some additional action configuration](https://github.com/gradle/actions/blob/main/dependency-submission/README.md#publishing-a-develocity-build-scan-from-your-dependency-submission-workflow).

Q. **I'm not seeing any security vulnerabilities for any of my dependencies. How can I be sure this is working?**
A. First check that [Dependabot Alerts](https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts) are enabled for your repository. Without this, your dependency graph may be populated but you won't see which dependencies are potentially vulnerable.

Q. **How can I use Dependabot Security Updates to generate a PR to update my vulnerable dependencies?**
A. In most cases, Dependabot Security Updates is not able to automatically generate a PR to update a dependency version. This can be due to the vulnerable dependency being transitive (and so there's nowhere to update the version), or because the Dependabot implementation doesn't understand how to update the version.
In a few select cases the Dependabot security update will work and generate a PR. eg when a direct dependency version is listed in a TOML dependency catalog.

Q. **I'm getting many false positive Dependabot Alerts for dependencies that aren't used by my project. Why are these dependencies being reported?**
A. The `dependency-submission` action resolves all of the dependencies in your build. This includes plugins, dependencies you've declared, test dependencies, and all transitive dependencies of these. It doesn't matter how the dependencies are declared: the ones being resolved by Gradle are the ones being reported.

Many people are surprised to see what dependencies are actually being resolved when they run their builds, but I'm yet to see a case where the dependencies being reported are actually incorrect. If you can confirm that a dependency is really being reported and not resolved by your project, then I can investigate further.

Please [follow the instructions here](https://github.com/gradle/actions/blob/main/dependency-submission/README.md#finding-the-source-of-a-dependency-vulnerability) to identify the source of the dependency version that is being reported.

Once you have worked out why it is being resolved, you can either [update the dependency version](https://github.com/gradle/actions/blob/main/dependency-submission/README.md#updating-the-dependency-version) or [exclude it from the submitted dependency graph](https://github.com/gradle/actions/blob/main/dependency-submission/README.md#limiting-the-dependencies-that-appear-in-the-dependency-graph).

**Comment by oleg-nenashev** [comment]
I would suggest initializing the documentation structure under `docs/` (for each action or integrated) and putting it there

**Comment by bigdaz** [comment]
Implemented in #110
